import type { Camera, Zone } from "@/features/inventory/types/interactive-map";

export const zones: Zone[] = [
  {
    id: "H",
    name: "Shelf H",
    type: "shelf",
    product: "Baby Formula",
    level: "Eye",
    x: 540,
    y: 92,
    width: 585,
    height: 68,
    status: "lowStock",
    traffic: 118,
    interactions: 41,
    stock: 5,
    conversion: 14.2,
    shelfValue: 2800,
    capacity: 24,
    insight: "Top shelf is running low. Refill soon to prevent stock-out.",
  },
  {
    id: "E",
    name: "Shelf E",
    type: "shelf",
    product: "Olive Oil",
    level: "Hand",
    x: 540,
    y: 258,
    width: 585,
    height: 68,
    status: "hot",
    traffic: 161,
    interactions: 60,
    stock: 17,
    conversion: 15.7,
    shelfValue: 9200,
    capacity: 30,
    insight: "Upper middle shelf with strong visibility and good customer pickup.",
  },
  {
    id: "D",
    name: "Shelf D",
    type: "shelf",
    product: "Greek Yogurt",
    level: "Waist",
    x: 540,
    y: 328,
    width: 585,
    height: 68,
    status: "normal",
    traffic: 137,
    interactions: 39,
    stock: 29,
    conversion: 11.6,
    shelfValue: 10500,
    capacity: 40,
    insight: "Moderate interaction. Suitable for routine essentials.",
  },
  {
    id: "C",
    name: "Shelf C",
    type: "shelf",
    product: "Instant Noodles",
    level: "Bottom",
    x: 540,
    y: 535,
    width: 585,
    height: 68,
    status: "warning",
    traffic: 152,
    interactions: 57,
    stock: 26,
    conversion: 8.9,
    shelfValue: 8300,
    capacity: 36,
    insight: "Good engagement, but weaker conversion. Review pricing or placement.",
  },
  {
    id: "B",
    name: "Shelf B",
    type: "shelf",
    product: "Sparkling Water",
    level: "Eye",
    x: 540,
    y: 605,
    width: 585,
    height: 68,
    status: "normal",
    traffic: 146,
    interactions: 43,
    stock: 31,
    conversion: 12.2,
    shelfValue: 11200,
    capacity: 42,
    insight: "Stable mid-store shelf with healthy activity.",
  },
  {
    id: "A",
    name: "Shelf A",
    type: "shelf",
    product: "Snack Bars",
    level: "Hand",
    x: 540,
    y: 795,
    width: 585,
    height: 68,
    status: "hot",
    traffic: 182,
    interactions: 64,
    stock: 22,
    conversion: 18.4,
    shelfValue: 13800,
    capacity: 32,
    insight: "Strong traffic near entrance. Good shelf for fast-moving products.",
  },
  {
    id: "G",
    name: "Shelf G",
    type: "wallShelf",
    product: "Fruit Juice",
    level: "Waist",
    x: 1445,
    y: 92,
    width: 82,
    height: 375,
    status: "warning",
    traffic: 129,
    interactions: 34,
    stock: 19,
    conversion: 7.8,
    shelfValue: 6100,
    capacity: 28,
    insight: "Visible from the right aisle, but conversion is soft. Improve signage.",
  },
  {
    id: "F",
    name: "Shelf F",
    type: "wallShelf",
    product: "Rice Bags",
    level: "Bottom",
    x: 1445,
    y: 503,
    width: 82,
    height: 360,
    status: "normal",
    traffic: 121,
    interactions: 28,
    stock: 44,
    conversion: 10.9,
    shelfValue: 7400,
    capacity: 60,
    insight: "Side-wall shelf. Reliable but lower dwell time than center aisles.",
  },
  {
    id: "COUNTER_1",
    name: "Counter 1",
    type: "counter",
    product: "Candy Packs",
    level: "Hand",
    x: 222,
    y: 246,
    width: 112,
    height: 265,
    status: "normal",
    traffic: 88,
    interactions: 0,
    stock: null,
    conversion: null,
    shelfValue: null,
    capacity: null,
    insight: "Service counter area. Useful for assisted sales and cashier support.",
  },
  {
    id: "COUNTER_2",
    name: "Counter 2",
    type: "counter",
    product: "Travel Batteries",
    level: "Hand",
    x: 222,
    y: 539,
    width: 112,
    height: 265,
    status: "normal",
    traffic: 91,
    interactions: 0,
    stock: null,
    conversion: null,
    shelfValue: null,
    capacity: null,
    insight: "Second counter close to entrance flow.",
  },
  {
    id: "ENTRANCE",
    name: "Entrance",
    type: "entrance",
    product: "Promo Bundle",
    level: "Eye",
    x: 332,
    y: 804,
    width: 128,
    height: 138,
    status: "normal",
    traffic: 322,
    interactions: 0,
    stock: null,
    conversion: null,
    shelfValue: null,
    capacity: null,
    insight: "Main entry point. Prime area for promotions and wayfinding.",
  },
];

export const cameras: Camera[] = [
  { id: "cam-1", x: 242, y: 96, rotate: 50 },
  { id: "cam-2", x: 520, y: 166, rotate: 0 },
  { id: "cam-3", x: 1110, y: 260, rotate: -180 },
  { id: "cam-4", x: 512, y: 404, rotate: 0 },
  { id: "cam-5", x: 1110, y: 540, rotate: -180 },
  { id: "cam-6", x: 512, y: 670, rotate: 0 },
  { id: "cam-7", x: 1110, y: 800, rotate: -180 },
  { id: "cam-8", x: 1450, y: 90, rotate: 90 },
  { id: "cam-9", x: 1410, y: 850, rotate: -90 },
];

export const selectedDefault = zones.find((zone) => zone.id === "C") ?? zones[0];
